# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.provider 'virtualbox' do |vb|
    vb.name = 'Kali'
    vb.memory = 4096
    vb.gui = true
  end

  config.vm.box = "kalilinux/rolling"
  config.vm.hostname = "kali"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "private_network", type: "dhcp", name: "vboxnet0", adapter: 2
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.graceful_halt_timeout = 5
end
