Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

 config.vm.provider 'virtualbox' do |vb|
    vb.memory = '4096'
    vb.name = 'Kali'
  end

  config.vm.network "private_network", type: "dhcp", name: "vboxnet0", adapter: 2
end
