# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.provider 'virtualbox' do |vb|
    vb.name = 'Kali'
    vb.memory = 1024
  end

  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "2023.4.0"
  config.vm.hostname = "kali"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "introsec"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.graceful_halt_timeout = 5
end
