
Vagrant.configure("2") do |config|

  config.vm.define "u1404_fsperm_ssh"
  config.vm.hostname = "u1404-fsperm-ssh"

  config.vm.box = "bento/ubuntu-14.04"
  config.vm.box_version = "201808.24.0"

  config.vm.provider :libvirt do |libvirt, override|
    override.vm.box = "peru/ubuntu-14.04-server-amd64"
    override.vm.box_version = "20190901.01"
    libvirt.memory = 2048
  end

  config.ssh.username = 'vagrant'
  config.vm.network "forwarded_port", guest: 21, host:2121

  # Disable NFS sharing (==> default: Mounting NFS shared folders...)
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true

  config.vm.provision "file", source: "files", destination: "/home/vagrant/"
  config.vm.provision "shell", path: "provision.sh"

  config.vm.graceful_halt_timeout = 2
end

