Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.box_version = "201808.24.0"

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048'
    vb.name = 'Ubuntu 14.04 fsperm'
  end

  config.vm.network "forwarded_port", guest: 21, host:2121

  config.vm.provision "file", source: "files", destination: "/home/vagrant/"
  config.vm.provision "shell", path: "provision.sh"

  config.vm.graceful_halt_timeout = 2
end
