# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'Ubuntu 14.04 fsperm'
    vb.memory = '2048'
    vb.gui = true
  end

  config.vm.box = "bento/ubuntu-14.04"
  config.vm.box_version = "201808.24.0"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "forwarded_port", guest: 21, host:2121
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.graceful_halt_timeout = 5

  # provision
  config.vm.provision "file", source: "files", destination: "/home/vagrant/"
  config.vm.provision "shell", path: "provision.sh"
end
