# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'Ubuntu 14.04 fsperm'
    vb.memory = '1024'
  end

  config.vm.hostname = "ubuntu14-fsperm-ssh"

  config.vm.box = "bento/ubuntu-14.04"
  config.vm.box_version = "201808.24.0"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "forwarded_port", guest: 21, host:2121
  config.vm.graceful_halt_timeout = 5

  # Disable NFS sharing (==> default: Mounting NFS shared folders...)
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true

  # provision
  config.vm.provision "file", source: "files", destination: "/home/vagrant/"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", inline: "echo Rebooting...", reboot: true
end
