# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.name = 'Ubuntu 14.04 vulnerable'
    vb.memory = 2048
    vb.gui = true
  end

  config.vm.box = "rapid7/metasploitable3-ub1404"
  config.vm.hostname = "metasploitable3-ub1404"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "private_network", ip: "192.168.10.20", virtualbox__intnet: "introsec"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.graceful_halt_timeout = 5
end
